### ISSUE TITLE
Headers set on Base class do not override subclass headers.

### ISSUE THREAD

**Issue by lucasklaassen** [rails/activeresource#298] opened 2018-09-30 16:37 UTC
Let me preface this issue with the fact that there probably is a good reason for why this is working this way but I was confused by this functionality and think maybe a documentation update good help.

Here is a PR that includes a test that showcases what I was trying to do: https://github.com/rails/activeresource/pull/297

In my application controller I defined a method that would generate a JWT token and add it to the headers of my ActiveResource request. I wanted to do this on a global level since all the resources I would be reaching out to would need it to be set. I decided to add it to my own Base class that inherits from `ActiveResource::Base` and then create subclasses off of that Base class to capture my individual resources. What I noticed was that after I made an initial request using one of my subclasses, the header would cache on the subclass. Anytime I would try and update the headers on my Base class it wouldn't override the headers on the subclasses. So the headers were cached on all the requests being sent from my subclasses.

In order to get around this I explicitly set the headers on the subclass and that worked. Is there a way to globally set headers on a Base class and have then propagate down to the subclasses? Can this be done in a thread safe way? If not, should we update [this section of the documentation](https://github.com/rails/activeresource#authentication) to note that?

Here's a similar issue: https://github.com/rails/activeresource/issues/277

**Comment by jeremy** [comment] 2018-10-01 15:10
Duplicate of #277, let's discuss there.

**Closed by jeremy** 2018-10-01 15:10 UTC
